# ============================================
# DeepTutor Cloud Build Configuration
# ============================================
# CI/CD pipeline for building and deploying to Cloud Run
#
# Usage:
#   gcloud builds submit --config=cloudbuild.yaml
#
# Or trigger automatically via GitHub/GitLab integration
# ============================================

substitutions:
  _SERVICE_NAME: deeptutor
  _REGION: asia-southeast1
  _REPOSITORY: deeptutor-repo

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${BUILD_ID}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
      - '-f'
      - 'Dockerfile.cloudrun'
      - '.'
    timeout: '1800s'  # 30 minutes for build

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}'
    waitFor: ['build']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${BUILD_ID}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '3'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'LLM_BINDING=gemini,LLM_HOST=https://generativelanguage.googleapis.com/v1beta/openai/,EMBEDDING_BINDING=google,EMBEDDING_HOST=https://generativelanguage.googleapis.com/v1beta/openai/,EMBEDDING_DIMENSION=768'
      - '--set-secrets'
      - 'LLM_API_KEY=llm-api-key:latest,LLM_MODEL=llm-model:latest,EMBEDDING_API_KEY=embedding-api-key:latest,EMBEDDING_MODEL=embedding-model:latest'
      - '--execution-environment'
      - 'gen2'
    waitFor: ['push']

# Store images in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${BUILD_ID}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100

# Build timeout (45 minutes total)
timeout: '2700s'

# Tags for filtering in Cloud Console
tags:
  - 'deeptutor'
  - 'cloud-run'
  - 'production'
